Support for third-party tools
advanced-security/adjust-cvss pull request #3
Opened 2024-03-25 21:30 UTC by CallMeGreg

This PR adds support for tools (like Trivy and Checkmarx) that define their rules under:

`runs` --> `tool` --> `driver` --> `rules` 

instead of:

`runs` --> `tool` --> `extensions` --> `rules`

Fixes #2 , and tested for backwards compatibility with CodeQL.

2024-03-25 21:31 UTC, CallMeGreg commented
Big shout out to @therealkujo for helping with this PR ✨

2024-03-26 12:02 UTC, aegilops requested changes

2024-03-26 12:02 UTC, aegilops commented on adjust_cvss.py
> +            qip = rule.get('id', [])
Can you use variable names that explain themselves please? I don't known what qip represents here

2024-03-26 12:02 UTC, aegilops commented on adjust_cvss.py
> +                for idp, sp in args.patterns:
What are idp and sp here? Can they can expanded names please?

2024-03-26 14:38 UTC, CallMeGreg commented on adjust_cvss.py
> +            qip = rule.get('id', [])
Updated `qip` to `rule_id`. Technical debt from previous contributions 🙂 no better time to fix it tho!

2024-03-26 14:39 UTC, CallMeGreg commented on adjust_cvss.py
> +                for idp, sp in args.patterns:
Updated to `input_id_pattern` and `input_score_pattern`.

2024-03-26 19:58 UTC, aegilops approved these changes

2024-03-27 20:52 UTC, merged